basePath: /
definitions:
  CreateOrderRequest:
    properties:
      orderItems:
        items:
          $ref: '#/definitions/OrderItem'
        type: array
      storeId:
        type: string
    type: object
  CreateOrderResponse:
    properties:
      stripeClientSecret:
        type: string
    type: object
  CreateUserRequest:
    properties:
      firstname:
        type: string
      language_code:
        type: string
      lastname:
        type: string
    required:
    - firstname
    - language_code
    - lastname
    type: object
  GetOrdersResponse:
    properties:
      createdAt:
        type: string
      estimatedPickupTime:
        type: string
      googleMapsLink:
        type: string
      id:
        type: string
      isPaid:
        type: boolean
      orderItems:
        items:
          $ref: '#/definitions/OrderItem'
        type: array
      price:
        type: integer
      status:
        type: integer
      storeAddress:
        type: string
      storeDescription:
        type: string
      storeImageUrl:
        type: string
      storeName:
        type: string
      storePhoneNumber:
        type: string
    type: object
  GetStoreCategory:
    properties:
      description:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/GetStoreProduct'
        type: array
      sortOrder:
        type: integer
    type: object
  GetStoreOpeningHour:
    properties:
      dayOfWeek:
        type: integer
      endTimestamp:
        type: integer
      startTimestamp:
        type: integer
    type: object
  GetStoreProduct:
    properties:
      description:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      max:
        type: integer
      min:
        type: integer
      multiMax:
        type: integer
      multiply:
        type: integer
      name:
        type: string
      plu:
        type: string
      price:
        type: integer
      productType:
        type: integer
      products:
        items:
          $ref: '#/definitions/GetStoreProduct'
        type: array
      snoozed:
        type: boolean
      sortOrder:
        type: integer
      tax:
        type: integer
      visible:
        type: boolean
    type: object
  GetStoreResponse:
    properties:
      address:
        type: string
      averagePickupTime:
        type: integer
      averageReview:
        type: number
      categories:
        items:
          $ref: '#/definitions/GetStoreCategory'
        type: array
      description:
        type: string
      googleMapsLink:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      name:
        type: string
      openingHours:
        items:
          $ref: '#/definitions/GetStoreOpeningHour'
        type: array
      phoneNumber:
        type: string
      reviewCount:
        type: integer
    type: object
  GetStoresOverviewResponse:
    properties:
      address:
        type: string
      averagePickupTime:
        type: integer
      averageReview:
        type: number
      description:
        type: string
      googleMapsLink:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      isAvailable:
        type: boolean
      name:
        type: string
      phoneNumber:
        type: string
      reviewCount:
        type: integer
    type: object
  Menu:
    properties:
      categories:
        items:
          $ref: '#/definitions/GetStoreCategory'
        type: array
      opening_hours:
        items:
          $ref: '#/definitions/GetStoreOpeningHour'
        type: array
    type: object
  OrderItem:
    properties:
      id:
        type: string
      name:
        type: string
      plu:
        type: string
      price:
        type: integer
      quantity:
        type: integer
      subItems:
        items:
          $ref: '#/definitions/OrderItem'
        type: array
    type: object
  User:
    properties:
      createdAt:
        type: string
      firebaseId:
        type: string
      firstname:
        type: string
      id:
        type: string
      languageCode:
        type: string
      lastname:
        type: string
    type: object
  WhitelistRequest:
    properties:
      identifier:
        type: string
    required:
    - identifier
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the Crunch Backend API
  title: Crunch Backend API
  version: "1.0"
paths:
  /app/v1/orders:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/GetOrdersResponse'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Get all orders from a user
      tags:
      - orders
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreateOrderResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "409":
          description: Conflict
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Create Order for a store
      tags:
      - orders
  /app/v1/store/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Id of the store
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetStoreResponse'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Get menu for a given store
      tags:
      - store
  /app/v1/stores:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/GetStoresOverviewResponse'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Get all open stores
      tags:
      - stores
  /app/v1/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Get User associated with the given Firebase Token
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "409":
          description: Conflict
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - FirebaseToken: []
      summary: Create User associated with the given Firebase Token
      tags:
      - users
  /app/v1/whitelist:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/WhitelistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Check if identifier is whitelisted
      tags:
      - whitelist
  /dashboard/v1/menu:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Menu'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - Auth0Token: []
      summary: Get the menu for a store
      tags:
      - dashboard
  /dashboard/v1/orders:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/GetOrdersResponse'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - Auth0Token: []
      summary: Get all orders from a store
      tags:
      - dashboard
  /dashboard/v1/products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/GetStoreProduct'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - Auth0Token: []
      summary: Get all products from a store
      tags:
      - dashboard
securityDefinitions:
  Auth0Token:
    in: header
    name: Authorization
    type: apiKey
  FirebaseToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
